#ifndef CAMERAREGISTERS_H
#define CAMERAREGISTERS_H

//Register definitions from control register verilog file (in 16 bit word addresses)

#define SENSOR_CONTROL				 0x0000 /* 0      */
#define SENSOR_CLK_PHASE			 0x0004 /* 2      */
#define SENSOR_SYNC_TOKEN			 0x0008 /* 4      */
#define SENSOR_DATA_CORRECT			 0x000C /* 6      */
#define SENSOR_FIFO_START_W_THRESH	 0x0010 /* 8      */
#define SENSOR_FIFO_STOP_W_THRESH	 0x0014 /* 10     */
#define	IMAGER_FRAME_PERIOD			 0x001C /* 14     */
#define IMAGER_INT_TIME				 0x0020 /* 16     */
#define	SENSOR_SCI_CONTROL			 0x0024 /* 18     */
#define	SENSOR_SCI_ADDRESS			 0x0028 /* 20     */
#define	SENSOR_SCI_DATALEN			 0x002C /* 22     */
#define SENSOR_SCI_FIFO_WR_ADDR		 0x0030 /* 24     */
#define SENSOR_SCI_READ_DATA		 0x0034 /* 26     */

#define	SEQ_CTL						 0x0040 /* 32     */
#define	SEQ_STATUS					 0x0044 /* 34     */
#define	SEQ_FRAME_SIZE				 0x0048 /* 36     */
#define	SEQ_REC_REGION_START		 0x004C /* 38     */
#define	SEQ_REC_REGION_END			 0x0050 /* 40     */
#define	SEQ_LIVE_ADDR_0				 0x0054 /* 42     */
#define	SEQ_LIVE_ADDR_1				 0x0058 /* 44     */
#define	SEQ_LIVE_ADDR_2				 0x005C /* 46     */
#define	SEQ_TRIG_DELAY				 0x0060 /* 48     */
#define	SEQ_MD_FIFO_READ			 0x0064 /* 50     */

#define SENSOR_MAGIC_START_DELAY	 0x0068 /* 52     */
#define	SENSOR_LINE_PERIOD			 0x006C /* 54     */

#define TRIG_ENABLE					 0x00A0 /* 16'h50  */
#define TRIG_INVERT					 0x00A4 /* 16'h52  */
#define	TRIG_DEBOUNCE				 0x00A8 /* 16'h54  */

#define	IO_OUT_LEVEL_ADDRESS		 0x00AC /* 16'h56  */
#define	IO_OUT_SOURCE_ADDRESS		 0x00B0 /* 16'h58  */
#define	IO_OUT_INVERT_ADDRESS		 0x00B4 /* 16'h5A  */
#define	IO_IN_ADDRESS				 0x00B8 /* 16'h5C  */
#define	EXT_SHUTTER_CTL				 0x00BC /* 16'h5E  */

#define	SEQ_PGM_MEM_START			 0x0100 /* 16'h80  */
#define	SEQ_PGM_MEM_END				 0x01FE /* 16'hFF  */
#define GPMC_PAGE_OFFSET			 0x0200 /* 16'h100 */

#define DISPLAY_CTL					 0x0400 /* 16'h200 */
#define	DISPLAY_FRAME_ADDRESS		 0x0404 /* 16'h202 */
#define	DISPLAY_FPN_ADDRESS			 0x0408 /* 16'h204 */
#define DISPLAY_GAIN_ADDRESS		 0x040C /* 16'h206 */
#define DISPLAY_H_PERIOD_ADDRESS	 0x0410 /* 16'h208 */
#define DISPLAY_V_PERIOD_ADDRESS	 0x0414 /* 16'h20A */
#define DISPLAY_H_SYNC_LEN_ADDRESS	 0x0418 /* 16'h20C */
#define DISPLAY_V_SYNC_LEN_ADDRESS	 0x041C /* 16'h20E */
#define DISPLAY_H_BACK_PORCH_ADDRESS 0x0420 /* 16'h210 */
#define DISPLAY_V_BACK_PORCH_ADDRESS 0x0424 /* 16'h212 */
#define DISPLAY_H_RES_ADDRESS		 0x0428 /* 16'h214 */
#define DISPLAY_V_RES_ADDRESS		 0x042C /* 16'h216 */
#define DISPLAY_H_OUT_RES_ADDRESS	 0x0430 /* 16'h218 */
#define DISPLAY_V_OUT_RES_ADDRESS	 0x0440 /* 16'h220 */
#define DISPLAY_PEAKING_THRESH_ADDR  0x0444 /* 16'h222 */

#define CCM_11_ADDRESS				 0x04C0 /* 16'h260 */
#define CCM_12_ADDRESS				 0x04C4 /* 16'h262 */
#define CCM_13_ADDRESS				 0x04C8 /* 16'h264 */
#define CCM_21_ADDRESS				 0x04D0 /* 16'h268 */
#define CCM_22_ADDRESS				 0x04D4 /* 16'h26A */
#define CCM_23_ADDRESS				 0x04D8 /* 16'h26C */
#define CCM_31_ADDRESS				 0x04DC /* 16'h26E */
#define CCM_32_ADDRESS				 0x04E0 /* 16'h270 */
#define CCM_33_ADDRESS				 0x04E4 /* 16'h272 */

#define WL_DYNDLY_0_ADDRESS			 0x0500 /* 16'h280 */
#define WL_DYNDLY_1_ADDRESS			 0x0502 /* 16'h281 */
#define WL_DYNDLY_2_ADDRESS			 0x0504 /* 16'h282 */
#define WL_DYNDLY_3_ADDRESS			 0x0506 /* 16'h283 */

#define MMU_CONFIG_ADDRESS           0x0520 /* 16'h290 */

#define SYSTEM_RESET				 0x0600 /* 16'h300 */
#define VERSION						 0x0604 /* 16'h302 */
#define	DCG_MEM_START				 0x0C00 /* 16'h800 */
#define	DCG_MEM_END					 0x2000 /* 16'h1000 */



//Image sensor control register
#define	IMAGE_SENSOR_CONTROL_ADDR		0

#define	IMAGE_SENSOR_RESET_MASK			0x1
#define IMAGE_SENSOR_EVEN_TIMESLOT_MASK 0x2

//Phase control register

#define IMAGE_SENSOR_CLK_PHASE_ADDR		(SENSOR_CLK_PHASE)
#define IMAGE_SENSOR_CLK_PHASE_OFFSET	0

//Sync Token Register
#define IMAGE_SENSOR_SYNC_TOKEN_ADDR	(SENSOR_SYNC_TOKEN)

//Data Correct
//Indicates data channels 11:0 and sync are correct
// Format: data[11], data[10], ... data[0], sync

#define IMAGE_SENSOR_DATA_CORRECT_ADDR	(SENSOR_DATA_CORRECT)

//Image data write path FIFO thresholds for start and stop of data write to ram

#define IMAGE_SENSOR_FIFO_START_W_THRESH_ADDR	(SENSOR_FIFO_START_W_THRESH)
#define IMAGE_SENSOR_FIFO_STOP_W_THRESH_ADDR	(SENSOR_FIFO_STOP_W_THRESH)

#define	IMAGER_FRAME_PERIOD_ADDR			(IMAGER_FRAME_PERIOD)
#define IMAGER_INT_TIME_ADDR				(IMAGER_INT_TIME)

#define	SENSOR_SCI_CONTROL_ADDR			(SENSOR_SCI_CONTROL)
#define SENSOR_SCI_CONTROL_RUN_MASK		0x1						//Write 1 to start, reads 1 while busy, 0 when done
#define SENSOR_SCI_CONTROL_RW_MASK		0x2						//Read == 1, Write == 0
#define SENSOR_SCI_CONTROL_FIFO_FULL_MASK	0x4					//1 indicates FIFO is full
#define	SENSOR_SCI_ADDRESS_ADDR			(SENSOR_SCI_ADDRESS)
#define	SENSOR_SCI_DATALEN_ADDR			(SENSOR_SCI_DATALEN)
#define SENSOR_SCI_FIFO_WR_ADDR_ADDR	(SENSOR_SCI_FIFO_WR_ADDR)
#define SENSOR_SCI_READ_DATA_ADDR		(SENSOR_SCI_READ_DATA)

#define	SEQ_CTL_ADDR					(SEQ_CTL)
#define	SEQ_CTL_SW_TRIG_MASK			0x1
#define SEQ_CTL_START_REC_MASK			0x2
#define	SEQ_CTL_STOP_REC_MASK			0x4
#define	SEQ_CTL_TRIG_DELAY_MODE_MASK	0x8

#define	SEQ_STATUS_ADDR					(SEQ_STATUS)
#define	SEQ_STATUS_RECORDING_MASK		0x1
#define	SEQ_STATUS_MD_FIFO_EMPTY_MASK	0x2

#define	SEQ_FRAME_SIZE_ADDR				(SEQ_FRAME_SIZE)
#define	SEQ_REC_REGION_START_ADDR		(SEQ_REC_REGION_START)
#define	SEQ_REC_REGION_END_ADDR			(SEQ_REC_REGION_END)
#define	SEQ_LIVE_ADDR_0_ADDR			(SEQ_LIVE_ADDR_0)
#define	SEQ_LIVE_ADDR_1_ADDR			(SEQ_LIVE_ADDR_1)
#define	SEQ_LIVE_ADDR_2_ADDR			(SEQ_LIVE_ADDR_2)
#define	SEQ_TRIG_DELAY_ADDR				(SEQ_TRIG_DELAY)
#define	SEQ_MD_FIFO_READ_ADDR			(SEQ_MD_FIFO_READ)
#define	SEQ_PGM_MEM_START_ADDR			(SEQ_PGM_MEM_START)

#define SENSOR_MAGIC_START_DELAY_ADDR	(SENSOR_MAGIC_START_DELAY)
#define	SENSOR_LINE_PERIOD_ADDR			(SENSOR_LINE_PERIOD)

#define	TRIG_ENABLE_ADDR				(TRIG_ENABLE)
#define	TRIG_INVERT_ADDR				(TRIG_INVERT)
#define	TRIG_DEBOUNCE_ADDR				(TRIG_DEBOUNCE)

#define	IO_OUT_LEVEL_ADDR				(IO_OUT_LEVEL_ADDRESS)		//1 outputs high if selected (invert does not affect this)
#define	IO_OUT_SOURCE_ADDR				(IO_OUT_SOURCE_ADDRESS)		//1 selects int time, 0 selects IO_OUT_LEVEL
#define	IO_OUT_INVERT_ADDR				(IO_OUT_INVERT_ADDRESS)		//1 inverts int time signal
#define	IO_IN_ADDR						(IO_IN_ADDRESS)		//1 inverts int time signal

#define	EXT_SHUTTER_CTL_ADDR			(EXT_SHUTTER_CTL)
#define	EXT_SH_TRIGD_EXP_EN_MASK		0x1
#define	EXT_SH_TRIGD_EXP_EN_OFFSET		0
#define	EXT_SH_GATING_EN_MASK			0x2
#define	EXT_SH_GATING_EN_OFFSET			1
#define	EXT_SH_SRC_EN_MASK				0x1C
#define	EXT_SH_SRC_EN_OFFSET			2

#define GPMC_PAGE_OFFSET_ADDR			(GPMC_PAGE_OFFSET)

#define DISPLAY_CTL_ADDR				(DISPLAY_CTL)
#define DISPLAY_CTL_ADDRESS_SEL_OFFSET	0
#define DISPLAY_CTL_SCALER_NN_OFFSET	1
#define DISPLAY_CTL_SYNC_INH_OFFSET		2
#define DISPLAY_CTL_READOUT_INH_OFFSET	3
#define DISPLAY_CTL_COLOR_MODE_OFFSET	4
#define DISPLAY_CTL_FOCUS_PEAK_EN_OFFSET	5
#define DISPLAY_CTL_FOCUS_PEAK_COLOR_OFFSET	6
#define DISPLAY_CTL_ZEBRA_EN_OFFSET		9

#define DISPLAY_CTL_ADDRESS_SEL_MASK	(1 << DISPLAY_CTL_ADDRESS_SEL_OFFSET)
#define DISPLAY_CTL_SCALER_NN_MASK		(1 << DISPLAY_CTL_SCALER_NN_OFFSET)
#define DISPLAY_CTL_SYNC_INH_MASK		(1 << DISPLAY_CTL_SYNC_INH_OFFSET)
#define DISPLAY_CTL_READOUT_INH_MASK	(1 << DISPLAY_CTL_READOUT_INH_OFFSET)
#define DISPLAY_CTL_COLOR_MODE_MASK		(1 << DISPLAY_CTL_COLOR_MODE_OFFSET)
#define DISPLAY_CTL_FOCUS_PEAK_EN_MASK	(1 << DISPLAY_CTL_FOCUS_PEAK_EN_OFFSET)
#define DISPLAY_CTL_FOCUS_PEAK_COLOR_MASK	(7 << DISPLAY_CTL_FOCUS_PEAK_COLOR_OFFSET)
#define DISPLAY_CTL_ZEBRA_EN_MASK		(1 << DISPLAY_CTL_ZEBRA_EN_OFFSET)

#define	DISPLAY_FRAME_ADDRESS_ADDR		(DISPLAY_FRAME_ADDRESS)
#define	DISPLAY_FPN_ADDRESS_ADDR		(DISPLAY_FPN_ADDRESS)
#define DISPLAY_GAIN_ADDR				(DISPLAY_GAIN_ADDRESS)
#define DISPLAY_H_PERIOD_ADDR			(DISPLAY_H_PERIOD_ADDRESS)
#define DISPLAY_V_PERIOD_ADDR			(DISPLAY_V_PERIOD_ADDRESS)
#define DISPLAY_H_SYNC_LEN_ADDR			(DISPLAY_H_SYNC_LEN_ADDRESS)
#define DISPLAY_V_SYNC_LEN_ADDR			(DISPLAY_V_SYNC_LEN_ADDRESS)
#define DISPLAY_H_BACK_PORCH_ADDR		(DISPLAY_H_BACK_PORCH_ADDRESS)
#define DISPLAY_V_BACK_PORCH_ADDR		(DISPLAY_V_BACK_PORCH_ADDRESS)
#define DISPLAY_H_RES_ADDR				(DISPLAY_H_RES_ADDRESS)
#define DISPLAY_V_RES_ADDR				(DISPLAY_V_RES_ADDRESS)
#define DISPLAY_H_OUT_RES_ADDR			(DISPLAY_H_OUT_RES_ADDRESS)
#define DISPLAY_V_OUT_RES_ADDR			(DISPLAY_V_OUT_RES_ADDRESS)
//#define DISPLAY_PEAKING_THRESH_ADDR		(DISPLAY_PEAKING_THRESH)

#define CCM_11_ADDR						(CCM_11_ADDRESS)
#define CCM_12_ADDR						(CCM_12_ADDRESS)
#define CCM_13_ADDR						(CCM_13_ADDRESS)
#define CCM_21_ADDR						(CCM_21_ADDRESS)
#define CCM_22_ADDR						(CCM_22_ADDRESS)
#define CCM_23_ADDR						(CCM_23_ADDRESS)
#define CCM_31_ADDR						(CCM_31_ADDRESS)
#define CCM_32_ADDR						(CCM_32_ADDRESS)
#define CCM_33_ADDR						(CCM_33_ADDRESS)

#define WL_DYNDLY_0_ADDR				(WL_DYNDLY_0_ADDRESS)
#define WL_DYNDLY_1_ADDR				(WL_DYNDLY_1_ADDRESS)
#define WL_DYNDLY_2_ADDR				(WL_DYNDLY_2_ADDRESS)
#define WL_DYNDLY_3_ADDR				(WL_DYNDLY_3_ADDRESS)

#define MMU_CONFIG_ADDR                 (MMU_CONFIG_ADDRESS)
#define MMU_INVERT_CS                   1
#define MMU_SWITCH_STUFFED              2


#define SYSTEM_RESET_ADDR				(SYSTEM_RESET)

#define FPGA_VERSION_ADDR				(VERSION)

#define	DCG_MEM_START_ADDR				(DCG_MEM_START)



#endif // CAMERAREGISTERS_H


