/*
 * This file was NOT generated by qdbusxml2cpp version 0.7
 * Command line WOULD HAVE BEEN qdbusxml2cpp -p chronosControlInterface control.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is NOT an auto-generated file.
 * Edit this file manually!
 */

#ifndef CHRONOSCONTROLINTERFACE_H_1517442513
#define CHRONOSCONTROLINTERFACE_H_1517442513

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface com.krontech.chronos.control
 */
class ComKrontechChronosControlInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.krontech.chronos.control"; }

public:
    ComKrontechChronosControlInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);
    ~ComKrontechChronosControlInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QVariantMap> getCameraData()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getCameraData"), argumentList);
    }

    inline QDBusPendingReply<QVariantMap> getSensorData()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getSensorData"), argumentList);
    }

    inline QDBusPendingReply<QVariantMap> getSensorSettings()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getSensorSettings"), argumentList);
    }

	inline QDBusPendingReply<QVariantMap> getSensorLimits()
    {
        QList<QVariant> argumentList;
		qDebug("GSL!");
		//return asyncCallWithArgumentList(QLatin1String("getSensorLimits"), argumentList);
		return asyncCallWithArgumentList(QLatin1String("getSensorLimits"), argumentList);
		//return asyncCallWithArgumentList(QLatin1String("getSensorSettings2"), argumentList);
	}

    inline QDBusPendingReply<QVariantMap> getWhiteBalance()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("getWhiteBalance"), argumentList);
    }

    inline QDBusPendingReply<QVariantMap> setWhiteBalance(const QVariantMap &args)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(args);
        qDebug() << "setting WB: " << argumentList;
        return asyncCallWithArgumentList(QLatin1String("setWhiteBalance"), argumentList);
    }

    inline QDBusPendingReply<QVariantMap> status(const QVariantMap &args)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(args);
		//qDebug() << "getting status: " << argumentList;
        return asyncCallWithArgumentList(QLatin1String("status"), argumentList);
    }

    inline QDBusPendingReply<QVariantMap> setDescription(const QVariantMap &args)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(args);
        qDebug() << "setDescription: " << argumentList;
        return asyncCallWithArgumentList(QLatin1String("setDescription"), argumentList);
    }

    inline QDBusPendingReply<QVariantMap> reinitSystem(const QVariantMap &args)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(args);
        qDebug() << "reinitSystem: " << argumentList;
        return asyncCallWithArgumentList(QLatin1String("reinitSystem"), argumentList);
    }

    inline QDBusPendingReply<QVariantMap> setSensorSettings(const QVariantMap &args)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(args);
        qDebug() << "setSensorSettings: " << argumentList;
        return asyncCallWithArgumentList(QLatin1String("setSensorSettings"), argumentList);
    }

	inline QDBusPendingReply<QVariantMap> setIoMapping(const QVariantMap &args)
	{
		QList<QVariant> argumentList;
		argumentList << qVariantFromValue(args);
		qDebug() << "setIoMapping: " << argumentList;
		return asyncCallWithArgumentList(QLatin1String("setIoMapping"), argumentList);
	}


	inline QDBusPendingReply<QVariantMap> getIoMapping(const QVariantMap &args)
	{
		QList<QVariant> argumentList;
		argumentList << qVariantFromValue(args);
		qDebug("GIM");
		//return asyncCallWithArgumentList(QLatin1String("getIoMapping"), argumentList);
		return asyncCallWithArgumentList(QLatin1String("calibrate"), argumentList);
	}


	inline QDBusPendingReply<QVariantMap> calibrate(const QVariantMap &args)
	{
		QList<QVariant> argumentList;
		argumentList << qVariantFromValue(args);
		qDebug() << "calibrate: " << argumentList;
		return asyncCallWithArgumentList(QLatin1String("calibrate"), argumentList);
	}

	inline QDBusPendingReply<QVariantMap> setSensorTiming(const QVariantMap &args)
	{
		QList<QVariant> argumentList;
		argumentList << qVariantFromValue(args);
		qDebug() << "setSensorTiming: " << argumentList;
		return asyncCallWithArgumentList(QLatin1String("setSensorTiming"), argumentList);
	}

	inline QDBusPendingReply<QVariantMap> getColorMatrix()
	{
		QList<QVariant> argumentList;
		return asyncCallWithArgumentList(QLatin1String("getColorMatrix"), argumentList);
	}

	inline QDBusPendingReply<QVariantMap> setColorMatrix()
	{
		QList<QVariant> argumentList;
		return asyncCallWithArgumentList(QLatin1String("setColorMatrix"), argumentList);
	}

//---------------

	inline QDBusPendingReply<QVariantMap> startRecord(const QVariantMap &args)
	{
		QList<QVariant> argumentList;
		qDebug() << "startRecord ";
		argumentList << qVariantFromValue(args);
		return asyncCallWithArgumentList(QLatin1String("startRecord"), argumentList);
	}

	inline QDBusPendingReply<QVariantMap> stopRecord(const QVariantMap &args)
	{
		QList<QVariant> argumentList;
		qDebug() << "stopRecord ";
		argumentList << qVariantFromValue(args);
		return asyncCallWithArgumentList(QLatin1String("stopRecord"), argumentList);
	}

	inline QDBusPendingReply<QVariantMap> dbusGetIoCapabilities()
	{
		QList<QVariant> argumentList;
		qDebug() << "dbusGetIoCapabilities";
		return asyncCallWithArgumentList(QLatin1String("dbusGetIoCapabilities"), argumentList);
	}

	inline QDBusPendingReply<QVariantMap> getCalCapabilities()
	{
		QList<QVariant> argumentList;
		qDebug() << "getCalCapabilities";
		return asyncCallWithArgumentList(QLatin1String("getCalCapabilities"), argumentList);
	}

	inline QDBusPendingReply<QVariantMap> getSequencerCapabilities()
	{
		QList<QVariant> argumentList;
		qDebug() << "getSequencerCapabilities";
		return asyncCallWithArgumentList(QLatin1String("getSequencerCapabilities"), argumentList);
	}

	inline QDBusPendingReply<QVariantMap> getSensorCapabilities()
	{
		QList<QVariant> argumentList;
		qDebug() << "getSensorCapabilities";
		return asyncCallWithArgumentList(QLatin1String("getSensorCapabilities"), argumentList);
	}

	inline QDBusPendingReply<QVariantMap> setSequencerProgram(const QVariantMap &args)
	{
		QList<QVariant> argumentList;
		argumentList << qVariantFromValue(args);
		qDebug() << "setSequencerProgram" << argumentList;
		return asyncCallWithArgumentList(QLatin1String("setSequencerProgram"), argumentList);
	}


	inline QDBusPendingReply<QVariantMap> getSequencerProgram(const QVariantMap &args)
	{
		QList<QVariant> argumentList;
		qDebug() << "getSequencerProgram";
		argumentList << qVariantFromValue(args);
		return asyncCallWithArgumentList(QLatin1String("getSequencerProgram"), argumentList);
	}






    inline QDBusPendingReply<QVariantMap> get_timing_limits(const QVariantMap &args)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(args);
        return asyncCallWithArgumentList(QLatin1String("get_timing_limits"), argumentList);
    }

    inline QDBusPendingReply<QVariantMap> get_video_settings()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("get_video_settings"), argumentList);
    }

    inline QDBusPendingReply<> set_video_settings(const QVariantMap &data)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(data);
        return asyncCallWithArgumentList(QLatin1String("set_video_settings"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

/*
 * Proxy class for interface org.freedesktop.DBus.Introspectable
 */
class OrgFreedesktopDBusIntrospectableInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.DBus.Introspectable"; }

public:
    OrgFreedesktopDBusIntrospectableInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OrgFreedesktopDBusIntrospectableInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> Introspect()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("Introspect"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

/*
 * Proxy class for interface org.freedesktop.DBus.Properties
 */
class OrgFreedesktopDBusPropertiesInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.DBus.Properties"; }

public:
    OrgFreedesktopDBusPropertiesInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~OrgFreedesktopDBusPropertiesInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QDBusVariant> Get(const QString &interface, const QString &propname)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(interface) << qVariantFromValue(propname);
        return asyncCallWithArgumentList(QLatin1String("Get"), argumentList);
    }

    inline QDBusPendingReply<QVariantMap> GetAll(const QString &interface)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(interface);
        return asyncCallWithArgumentList(QLatin1String("GetAll"), argumentList);
    }

    inline QDBusPendingReply<> Set(const QString &interface, const QString &propname, const QDBusVariant &value)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(interface) << qVariantFromValue(propname) << qVariantFromValue(value);
        return asyncCallWithArgumentList(QLatin1String("Set"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

namespace com {
  namespace krontech {
    namespace chronos {
      typedef ::ComKrontechChronosControlInterface control;
    }
  }
}
namespace org {
  namespace freedesktop {
    namespace DBus {
      typedef ::OrgFreedesktopDBusIntrospectableInterface Introspectable;
      typedef ::OrgFreedesktopDBusPropertiesInterface Properties;
    }
  }
}
#endif
